export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_FULFILLED = 'FETCH_LOCATIONS_FULFILLED';
export const FETCH_LOCATIONS_REJECTED = 'FETCH_LOCATIONS_REJECTED';
export const PUT_LOCATION = 'PUT_LOCATION';
export const PUT_LOCATION_FULFILLED = 'PUT_LOCATION_FULFILLED';
export const PUT_LOCATION_REJECTED = 'PUT_LOCATION_REJECTED';
